packages:
  - "apps/*"
  - "packages/ui"
  - "packages/shared/*"
  - "packages/tools/*"
  - "agent/agp"
  - "agent/skills"
  - "agent/mcp/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  bcrypt: true
  electron: true
  esbuild: true
  prisma: true
  protobufjs: true
  unrs-resolver: true
